name: tomluke2
favicon: null
layout_spectrum: 0.07970910426229239
typography_spectrum: 0.40921750315465033
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5202978947199881
  lightness: 0.44981982093304396
  saturation: 0.5934146784711629
  rhythmicContrast: 0.5850386379752308
purpose: []
